[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  branch = "master"

[[constraint]]
  name = "github.com/google/gopacket"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  branch = "master"

[[constraint]]
  name = "github.com/evilsocket/ftrace"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
